# Generated by Django 6.1.1 on 2026-09-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='programme',
        ),
        migrations.AddField(
            model_name='course',
            name='programmes',
            field=models.ManyToManyField(related_name='courses', to='students.programme'),
        ),
    ]
